### PR TITLE
GF: Repo structure and build script

### PR DESCRIPTION
**Pull request by RosaWagner**
**What I did in order to match GF spec:**

- Restructured repo
- Modified font metadata (instance naming has changed a bit, but I kept the same number of locations and there values)
- Added build script
- Rebuild fonts (but not NL version, we will see later how we automate this)

_Maybe take a look with glyph merge to see what changed ?_

**To do list:**

- [ ] Add comb-accents (as decomposed base glyphs)
- [ ] Turn current accents into composites of comb-accents
- [ ] Avoid overlapping, nested, transformed components (> decompose, merge and open corner)
- [ ] Avoid overlaps over overlaps
- [ ] Prefer one contour with open corners to 2 different contours (eg: the bar of the A can be merge with the diagonals with corners open)

### CODE REVIEW

**Comment by MicroJoe** [comment]
Thanks for this work, this is awesome. It would certainly help for packaging to distributions. At least on Debian, where we have the requirement to build from source in order for users to be able to tweak the font if needed.

I did not found a way to generate the -NL variants either.

**Comment by bulenkov** [comment]
@RosaWagner the script for generating NL version is here https://github.com/JetBrains/JetBrainsMono/tree/master/scripts

**Comment by philippnurullin** [comment]
Hi @RosaWagner . Thanks for the update. I have few questions regarding changes.
1. Why almost all PANOSE data was removed from instances?
2. What «Disable last change» is doing?
3. What is «Use line Breaks» is doing?
4. Why version was changed to 100?
5. Weight classes are changed. Can you give comments why this change is made? I understand that this is GF spec but i want to understand what logic is behind this.
6. Why «old» folder is needed? It won't help with dependent links. Maybe we can just delete the old structure?

**Comment by RosaWagner** [comment]
Hello @philippnurullin :)

1. Fontmake changes the panose informations to 0 everywhere because they are not so relevant nowadays (especially for fonts containing other scripts than Latin). In the case of a monospace font, [GF requires this though](https://github.com/googlefonts/gf-docs/tree/master/Spec#monospace-fonts). So I put the values that are required, but it was just to make an explicit change for you to see; in any case the build script is taking care of that wether the font contains this parameter are not.
2. Disable last change is useful for version control with git ([this is the conversation where it comes from](https://forum.glyphsapp.com/t/has-anyone-had-problems-working-with-glyphs-files-on-github/4077), but honestly I don't understand what it does ^^)
3. Use line breaks allows the license string etc. to contain line breaks (I think, I am not sure what it does actually but if you don't enable it Fontbakery is not happy)
4. Version is changed to 100 to not confuse it with the last version released, [please see the spec in that regards](https://github.com/googlefonts/gf-docs/tree/master/Spec#font-versioning). Since I changed the instance naming etc, it is kind of a "big" change
5. We are following the OpenType specifications to guarantee support by all OS and browsers. Only OTF need to have usWeightClass>250 (otherwise the font is blurry on Windows) and is it taken care in the build script. ([spec](https://github.com/googlefonts/gf-docs/tree/master/Spec#axes))

I kept your axis coordinates, although Semi Light is not an allowed instance name (referring to the opentype spec) so I twisted a bit the naming to make it acceptable.
You had: 
```
Extra Light — 100
Light — 220
Semi Light — 320
```
I changed it into:
```
Thin — 100
ExtraLight — 220
Light — 320
```

6. The "old" folder is not needed, but since I made changes in the font info that can maybe upset users, I wanted the previous version to still be accessible. This folder is only required when we update a font that is already on GF, all released versions have to be accessible somewhere. If you don't want to keep this version, just delete the folder (in any case, the fonts are still accessible in the release section). If you want to keep it, this is the repo structure that GF prefers.

Don't hesitate to tell me if something is not clear, I thought you were in holidays but I am of course available if you want to talk more about the font info stuff. I didn't modified any design thing since you wanted to take care of it ;)

**Comment by philippnurullin** [comment]
@RosaWagner Thanks for the quick reply!

- The accents update is in the process. After i finish with the upright weight can i send you the glyphs file for a quick review?
- What is the process of updating repo on GF when we make a new version (Maybe it's too soon for that, but it will be handy to understand the process)?

@bulenkov Do you think we need to make a new Release if we merge this PR? I think it will be wise to update all the font to the GF spec & only after that make a Release?

**Comment by RosaWagner** [comment]
It is probably better to merge this PR before making changes in the source files, otherwise it is going to create conflicts.

If you already made changes, I would suggest this process: 
1. save your version of the sources locally, don't commit/push them
2. merge my PR
3. use [MergeGlyph](https://glyphsapp.com/tools/mergeglyphs) to put your design changes into the new sources (so you can review the changes glyph by glyph without squashing the changes that I have made)
4. then push your changes with regular explicit descriptive commits

**Comment by philippnurullin** [comment]
Sounds logical. The problem i have with this approach is that in MergeGlyphs i will need to manually merge all 1000+ of them in 3 masters. The version in this PR is with the OT hints, so basically every glyph is different. Do you know a way to make this more wise?

**Comment by RosaWagner** [comment]
Merge/copy-paste just the font info stuff into your source file, and then replace it in the repo?

- Delete all your font info and you copy paste mine.
Don't forget to: 
- correct master names (and rename Extra Bold > ExtraBold without space, I forgot)
- rename your zero slash with a .zero suffix and enable "Generate feature automatically"
- correct instances parameters

We will review the vertical metrics at the end

**Comment by RosaWagner** [comment]
@philippnurullin I forgot to answer your question about the update. 
When you have new release, you address an issue in the google/fonts issue tracker with the title "Update JetBrainsMono" and in description you indicate the version, the repo, what's new etc. And you ping Dave, me or whoever you know working at GF ;)

**Comment by bulenkov** [comment]
@philippnurullin @RosaWagner we patched PANOSE data to make the font available in some popular Windows apps like Terminal, Microsoft Visual Studio, and others. We should check that removing/changing these PANOSE values will not break these apps.

**Comment by RosaWagner** [comment]
Of course, feel free to make some checks. If you see that it is disturbing and the panose values are the reason, report it to google/font, it will help us to adjust the spec. But the panose values are not removed, they are set to 0 (except for the proportion section which is monospaced in this case)

**Pull request merged**
