### PR TITLE
add powerline fonts

### PR DESCRIPTION
**Pull request by ryoppippi**
Hi!
At first, thank you for creating this awesome font! I love it!!

So, I just wanted to use it for my powerline on my shell and made this for powerline.
I just powerline font patcher but it looks great for me.
https://github.com/powerline/fontpatcher
If you are okay, please use this!

### CODE REVIEW

**Comment by ryoppippi** [comment]
It is only Powerline so lightweight

**Comment by seanghay** [comment]
> It is only Powerline so lightweight

I think it should be in `powerline/fonts` repository.

**Comment by ralph** [comment]
Duplicate of https://github.com/JetBrains/JetBrainsMono/pull/10

**Comment by ryoppippi** [comment]
https://github.com/JetBrains/JetBrainsMono/pull/28#issuecomment-575504009
Okay got it

**Comment by ryoppippi** [comment]
@seanghay  I think the `powerline/fonts` is not active for the last 2 years.
How can I deploy it?

**Comment by ryoppippi** [comment]
> Duplicate of #10

I don't think nerd fonts and powerline fonts are the same stuff.
Nerds version is really great, but there are some problems.
For example, My powerline version can show , but his nerds fonts cannot.

**Comment by ryoppippi** [comment]
> Extra Bold Italic

So should I fix the name of the ttf file?

**Comment by emanguy** [comment]
Nerd fonts has the apple icon at E711, F179, F302, and F534. It also includes the powerline symbols. If you're looking for a specific symbol, you can search it here: https://www.nerdfonts.com/cheat-sheet

**Comment by beanaroo** [comment]
"for Powerline" was convention of fonts that were patched to have Powerline glyphs. I don't believe that's necessary when they are included in the official font. Like box drawing and block characters.

**Comment by ryoppippi** [comment]
so close this?

**Comment by gsbhasin123** [comment]
@ryoppippi Powerline fonts are now in master.

**Comment by bulenkov** [comment]
Available in 1.0.2

**Pull request closed without merging**
