### PR TITLE
Updated requirements and dependencies

### PR DESCRIPTION
**Pull request by RosaWagner**
For the requirements.txt to be updated when run `pip-compile requirements.in`, you actually need to delete requirements.txt for it to not interfere with pip-compile. You can then reinstall your virtual environment.

### CODE REVIEW

**Comment by philippnurullin** [comment]
Hi @RosaWagner .
Sorry, a couple of obvious questions.
Why do i need to run `pip-compile requirements.in`?
Is it updating `requirements.txt` to have the latest versions of dependent scripts?
When do i need update the `requirements.txt`?

**Comment by RosaWagner** [comment]
Nothing you should worry about, Konstantin sent me an email to inform of a security alert because one dependency was not updated. If you want your environment to be updated you can :
- delete it the `env` directory
- recreate it in the repo `python3 -m venv env`
- then activate it `source env/bin/activate` 
- and then run `pip3 install -r requirements.txt`

**Comment by philippnurullin** [comment]
Thanks for clear instructions!

**Review by hungcon2301 — COMMENTED** [review]
#327

**Comment by philippnurullin** [comment]
Hi @RosaWagner when trying to run `build-webfonts.sh` it returns _permission denied_. The other scripts working like a clock. Do you know what's wrong?

**Comment by RosaWagner** [comment]
This script needs home-brew and webfonttools installed on your machine, in the script I added the GitHub repo to do so. BUT do you need woff ? If you would use only woff2, I could send you a script that uses python packages installed in the venv and you wouldn’t have to installed the other home-brew stuff…

——

Type design
Font engineering
Typography

+336 76 44 45 83
mail@rosaliewagner.com
www.rosaliewagner.com

**Comment by philippnurullin** [comment]
I don't know cases where is .woff prefered instead of .woff2 so we can provide only .woff2 and add the old one if some specific requests will occur.
So, yes please modify the `build-webfonts.sh` so it will export .eot + .woff2.

I tried to install webfonttools in the _venv_ (with homebrew). The installing sequence ends with error `Error: Permission denied @ apply2files - /usr/local/lib/docker/cli-plugins`.

**Comment by RosaWagner** [comment]
Yes, homebrew is not a python, so you can’t install webfontools in a python virtual environment.

**Comment by RosaWagner** [comment]
I was looking for oython packages to compress EOT but apparently it is pretty much dead also nowadays (for what I read online). What do you think if we do only woff2 until someone complains ?

**Comment by philippnurullin** [comment]
Well, ok. Let's wait for complains. )

**Comment by aviskase** [comment]
For anyone who like me used [css-tricks article](https://css-tricks.com/snippets/css/using-font-face/) as guidance and was surprised to see no woff in the last release:
https://caniuse.com/woff2 --- seems like we can live with woff2 if you don't need IE.

**Pull request merged**
