### PR TITLE
updated webfonts build script using only python packages

### PR DESCRIPTION
**Pull request by RosaWagner**
Last time I added "brotli" to the requirements, make sure you updated your virtual venv with it.

From the root of your repo with virtual env activated:
`pip3 install -r requirements.txt`

### CODE REVIEW

**Comment by philippnurullin** [comment]
After update the `build-webfonts.sh` returs the same error. 
`(env) UNIT-1427:JetBrainsMono philipp.nurullin$ /Users/philipp.nurullin/IdeaProjects/JetBrainsMono/sources/build-webfonts.sh 
-bash: /Users/philipp.nurullin/IdeaProjects/JetBrainsMono/sources/build-webfonts.sh: Permission denied`

**Comment by RosaWagner** [comment]
are you in bash ? (and not zsh)

**Comment by RosaWagner** [comment]
maybe this thread can help :  
https://www.reddit.com/r/osx/comments/dzbjhz/zsh_permission_denied/

**Comment by philippnurullin** [comment]
Yup. 
> `uild-webfonts.sh -bash:`

**Comment by RosaWagner** [comment]
So this thread. 
https://stackoverflow.com/questions/12276507/run-script-on-mac-prompt-permission-denied

Maybe you have to "sudo" the script etc since your are with catalina

**Comment by philippnurullin** [comment]
Yes, didn't try it with `sudo` after updating to the last PR. 
And this works!

Thanks a lot.

**Pull request merged**
