### PR TITLE
Add nerd font patched versions of base font

### LINKED ISSUE #2: REQ: Need a "Powerline" version
Powerline is a statusline plugin for vim, and provides statuslines and prompts for several other applications, including zsh, bash, tmux, IPython, Awesome and Qtile.

https://github.com/powerline/powerline

https://github.com/powerline/fonts

### PR DESCRIPTION
**Pull request by emanguy**
I used the Nerd Fonts patcher to patch extra glyphs into the base font so the font now has Powerline support. See sample:

image

Fixes #2

### CODE REVIEW

**Comment by pulberg** [comment]
Nice, I was just about to run `./font-patcher...` when I saw this, thanks for the effort!

**Comment by aaccioly** [comment]
Great stuff. Thanks!

**Comment by ollieatkinson** [comment]
Why are the icons small? 

image

**Comment by emanguy** [comment]
The icons are small with the official powerline fonts too, I've never found a way to fix it. For example, try the Ubuntu Mono powerline font and see if you see a difference: https://github.com/ryanoasis/nerd-fonts/tree/v2.0.0/patched-fonts/UbuntuMono

**Comment by emanguy** [comment]
Looking into this further, it looks like this occurs due to the way the font patcher handles Mono fonts. I can add a version where I don't use the monospace flag if you like. See: https://github.com/Powerlevel9k/powerlevel9k/issues/430#issuecomment-285836124

**Comment by ollieatkinson** [comment]
Thanks @emanguy - that makes sense. The font I was using before was patched as a non-monospaced font (Hasklug Nerd Font) which increased the size. However after reading the issue it seems we really shouldn't disable that because some emulators don't render the double character glyphs correctly

**Comment by pro-sumer** [comment]
Can JetBrains please (also) provide such a patched version whenever there's a new release?

(I have patched them myself for 1.0.0, 1.0.1, and 1.0.2, but it seems easier for -almost- everyone if JetBrains does the patching...)

**Comment by johnmccabe** [comment]
These are already patched as part of the nerd-fonts release, probably better to leave the font unaltered here.

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono

**Pull request closed without merging**
