### PR TITLE
Added new powerline symbols

### PR DESCRIPTION
**Pull request by FabSchwul**
Im using vim-airline plugin and I wanted a bevel on it, that is done using characters from E0B8 to E0BF, and JetBrains Mono doesn't support them. I added them with FontLab 7 as suggested in the readme.

### CODE REVIEW

**Comment by FabSchwul** [comment]
Tbh no idea why this fails, FontLab compiles them without problems

**Comment by FabSchwul** [comment]
Okey I tested it, though FontLab compiles it without problems, it changes glyps I haven't touched, so in the final result some of them look trimmed, blurry, etc.

I would appreciate some help, maybe tweaking some options in the export settings solves the problem but it's my first time with this software

**Comment by philippnurullin** [comment]
Hi @FabSchwul Looks like files will not work with our bild scripts.
You was misled by recommendation of FontLab 6 to work with source files. My bad, i will correct this. The source files are now in the .glyphs format so to work with them you need Glyphs app. So i think FL 6 "corrupts" files so they will not work with scripts.

You can create an issue and include the empty files only with glyphs you want to add and i will review them.
Or you can use Glyphs app for the new PR.

**Comment by FabSchwul** [comment]
Thanks! I will try it again with that app and see if it comes out uncorrupted

**Pull request closed without merging**
