### PR TITLE
Jet Brains Mono update

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello @philippnurullin! 
(feel free to tag anyone else in your team, if they are related to this update)

I'm Emma, I work with the Google Fonts team, as font onboarder, and I prepared that PR to answer to this issue: https://github.com/google/fonts/issues/7881

I reviewed the last version of the exported fonts, and found a couple of issues. You will find in the commits all the details.
They are only technical fixes, nothing concerns the design.

To fix that fail `🔥 FAIL Ensure the font supports case swapping for all its glyphs. `, I had to add the following glyphs: `ǏǑǓǛǗǙǕɛ`. For accented letters, they have been generated automatically, but for `ɛ`, it would need some design work. For now, I replaced it by the cap version, but feel free to update it for the next version.

So, if all is good for you, you can merge that PR, and I'll be happy then to push the update on the API server :)

Don't hesitate if you have any questions,

Cheers!

### CODE REVIEW

**Comment by philippnurullin** [comment]
Hi @emmamarichal 
Thanks for your contribution.

As I can see you modified the vertical metrics (Win). This will result in the massive problem four our users. We encountered a lot of feedback when the last time we increased it. A lot of developers are very sensitive about the amount of vertical space the font takes.
I totally understand why you setting the new values, but can we exclude this change from PR?

Have a nice day.

**Comment by emmamarichal** [comment]
Hi @philippnurullin!

- sorry for the late answer, I was off! -

We are also very vigilant about the regressions that modifications to vertical metrics can cause, as we understand that this can break certain layouts on the web. These are changes that we never accept in font updates because, as you mentioned, it's too risky. However, only changes to the `hhea` and `typo` metrics affect the rendering of websites, while changes to Win metrics are generally accepted and do not cause regressions. I have generated several HTML diff proofs, and these changes are indeed not noticeable.

**Comment by emmamarichal** [comment]
Hi @philippnurullin, 
Did you have time to think about this? Thanks!

**Comment by philippnurullin** [comment]
Thanks for your patience.
If we receive a lot of negative feedback from users, will it be possible to revert this changes and make another push to GF repository?

**Comment by emmamarichal** [comment]
@philippnurullin Yes sure! Win metrics changes don't cause regressions, and we can update them.

**Pull request merged**
